### PR TITLE
chore(layout): New initial page for the blog posts

### PR DESCRIPTION
**Pull request by xmnlab**
This PR aims to change the initial blog page layout:
new-blog

### CODE REVIEW

**Comment by xmnlab** [comment]
I will update more the layout in the following weeks :)

**Comment by esloch** [comment]
> I will update more the layout in the following weeks :)

Thanks Ivan!

**Comment by esloch** [comment]
I suggest centering the [main menu](https://github.com/OpenScienceLabs/opensciencelabs.github.io/blob/main/themes/osl/templates/index.tmpl#L20) relative to the page.

**Comment by xmnlab** [comment]
> I suggest centering the [main menu](https://github.com/OpenScienceLabs/opensciencelabs.github.io/blob/main/themes/osl/templates/index.tmpl#L20) relative to the page.

sounds good. as it is not related to the changes I made, do you mind opening an issue for that? I can do it in a follow-up PR :)

**Comment by xmnlab** [comment]
thanks for the review @esloch

**Pull request merged**
