### PR TITLE
Add social media entrypoints

### LINKED ISSUE #76: web: Create endpoints for aws sub-dominions
aws sub-dominions:

- [x] youtube
- [x] discord
- [x] calendar

endpoints  -> redirecionamento via js

- opensciencelabs.org/youtube -> https://www.youtube.com/channel/UCk01FMOEN6fIf4JLijMO68A
- opensciencelabs.org/discord -> https://discord.com/invite/mjAnW8BPck
- opensciencelabs.org/calendar -> https://calendar.google.com/calendar/u/0/r?cid=Y2VscHE1bThnMWQzcWRlMmFnNjRsazYyZG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

### PR DESCRIPTION
**Pull request by luabida**
fix #76 

Added plenty of social media redirects, used a `r-` to make it easier to recognize.

### CODE REVIEW

**Comment by xmnlab** [comment]
LGTM! just a question, what the "r-" prefix in the filename?

**Comment by luabida** [comment]
> what the "r-" prefix in the filename?


it should mean "redirection", I think it would be a bit confusing having all those redirections mixed up with the other html pages.

**Comment by xmnlab** [comment]
> > what the "r-" prefix in the filename?
> 
> it should mean "redirection", I think it would be a bit confusing having all those redirections mixed up with the other html pages.

it looks like R language XD

please remove the r- prefix, and in the future we can have something more fancy like: https://www.includecpp.org/discord/

**Comment by luabida** [comment]
Done. Do you think we should have these links for social medias in home page?

**Comment by xmnlab** [comment]
> Done. Do you think we should have these links for social medias in home page?

maybe it would be great to have it inside a footer (ex: https://labs.quansight.org/) 
could you open an issue for that? feel free to assigned it to yourself :) <3

**Review by xmnlab — APPROVED** [review]
LGTM. thanks!!

**Pull request merged**
